"""Core interfaces and contracts for Sovereign-Core."""

from app.core.interfaces.agents import (
    AgentResult,
    AgentState,
    AgentStep,
    BaseAgent,
)
from app.core.interfaces.audit import (
    AuditEvent,
    AuditEventType,
    BaseAuditLogger,
)
from app.core.interfaces.llm import (
    BaseLLMClient,
    ChatMessage,
    ChatRole,
    LLMConnectionError,
    LLMError,
    LLMHealthStatus,
    LLMModelNotFoundError,
    LLMResponse,
    LLMResponseError,
    LLMTimeoutError,
    LLMUsage,
    LLMValidationError,
    ModelInfo,
    StreamChunk,
)
from app.core.interfaces.rag import (
    BaseEmbeddingProvider,
    BaseRetriever,
    Document,
    SearchResult,
)
from app.core.interfaces.telemetry import (
    BaseTelemetryBroadcaster,
    BaseTelemetrySink,
    TelemetryEvent,
    TelemetryMetric,
    TelemetrySeverity,
    TelemetrySpan,
)
from app.core.interfaces.tools import (
    BaseTool,
    BaseToolRegistry,
    ToolDefinition,
    ToolResult,
)
from app.core.interfaces.workflows import (
    BaseWorkflowEngine,
    WorkflowEdge,
    WorkflowExecutionResult,
    WorkflowGraph,
    WorkflowNode,
    WorkflowNodeStatus,
    WorkflowNodeType,
    WorkflowStepResult,
)

__all__ = [
    "BaseLLMClient",
    "ChatMessage",
    "ChatRole",
    "LLMHealthStatus",
    "LLMError",
    "LLMConnectionError",
    "LLMTimeoutError",
    "LLMModelNotFoundError",
    "LLMResponseError",
    "LLMValidationError",
    "LLMResponse",
    "LLMUsage",
    "ModelInfo",
    "StreamChunk",
    "BaseEmbeddingProvider",
    "BaseRetriever",
    "Document",
    "SearchResult",
    "BaseTool",
    "BaseToolRegistry",
    "ToolDefinition",
    "ToolResult",
    "BaseAgent",
    "AgentState",
    "AgentStep",
    "AgentResult",
    "BaseAuditLogger",
    "AuditEvent",
    "AuditEventType",
    "BaseTelemetrySink",
    "BaseTelemetryBroadcaster",
    "TelemetryEvent",
    "TelemetrySpan",
    "TelemetryMetric",
    "TelemetrySeverity",
    "BaseWorkflowEngine",
    "WorkflowGraph",
    "WorkflowNode",
    "WorkflowEdge",
    "WorkflowNodeType",
    "WorkflowNodeStatus",
    "WorkflowStepResult",
    "WorkflowExecutionResult",
]
